# Etapa 1: construir Angular
FROM node:22-alpine AS build

WORKDIR /app

COPY web/package*.json ./

RUN npm ci

COPY web/ .

RUN npm run build


# Etapa 2: servir Angular con Nginx
FROM nginx:alpine

COPY infrastructure/nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/web/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]