spring:
  application:
    name: backend
  datasource:
    # Agregamos ?currentSchema=public al final
    url: jdbc:postgresql://localhost:5432/sst_db?currentSchema=public
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect


  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: public
    default-schema: public
    create-schemas: true

server:
  port: 8080

jwt:
  secret: rPqfXJ0ktpW2uY4nD5sV8zBcM7LhQaEe1Rg6UiNo9PmKxYsTzAvCxDfGhJkLmNpQr
  expiration: 3600000